In [1]:
import librosa
import numpy as np
import pandas as pd
from librosa import display
import matplotlib

In [2]:
#read csv file
temp = pd.read_csv('Atraining_normal_seg.csv')
temp

,Unnamed: 0,S1,S2,S1.1,S2.1,S1.2,S2.2,S1.3,S2.3,S1.4,...,S2.14,S1.15,S2.15,S1.16,S2.16,S1.17,S2.17,S1.18,S2.18,Unnamed: 39
0,201102081321.aif,10021.0,20759,35075,47244,62992,73729,88761,101646,115246,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201102260502.aif,NaN,11526,27941,42197,58163,71278,88955,102641,122028,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201103090635.aif,5366.0,17632,31432,44464,59030,71296,86629,99661,116527,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201103140132.aif,16358.0,29272,89539,105036,128282,142057,170469,183383,207490,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,201103140822.aif,3444.0,18080,44770,58545,84374,98149,123977,134309,157555,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,201103151912.aif,3244.0,12053,25829,61128,79208,96427,117090,133448,152389,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,201103221214.aif,27831.0,39095,54667,65601,81173,92769,108341,119605,135509,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,201104141251.aif,21189.0,32879,51876,64297,83294,96446,116904,129326,149053,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,201105011626.aif,NaN,2855,15497,23246,35299,43048,55962,63711,75764,...,287559.0,302195.0,307361.0,321136.0,328885.0,338355.0,347826.0,360740.0,381403.0,389151.0
9,201105021654.aif,24481.0,39781,79563,94863,126229,140765,169836,185136,215737,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,201105021804.aif,24107.0,35299,50796,61128,75764,86095,101593,112785,128282,...,390873.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,201105151450.aif,26679.0,40379,56964,71385,90853,105275,124743,138443,157912,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,201106111136.aif,19943.0,33239,56506,66953,87846,101142,122510,136280,159073,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,201106141148.aif,21449.0,31349,47849,58299,73698,84698,100648,112197,128147,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,201106210943.aif,5036.0,18466,40290,54839,73305,86735,106320,120310,141574,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,201106221418.aif,26126.0,40194,60291,72349,93116,105844,123261,138669,155416,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,201106221450.aif,2583.0,16358,38743,54240,74903,89539,111063,124838,147223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,201108011112.aif,25810.0,40993,63008,76672,98687,113110,135125,149548,170804,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,201108011114.aif,22774.0,37197,67562,81986,112351,127534,157899,172322,202687,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,201108011115.aif,23533.0,37197,59212,73635,95650,110074,132088,146512,168526,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,201108011118.aif,7591.0,20496,37197,50862,66803,78949,95650,107796,124497,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# load sample

data, sampling_rate = librosa.load('Atraining_normal/201102081321.wav', sr=44100 )
display.waveplot(data, sr=sampling_rate)

In [4]:
temp.shape

(21, 40)

In [5]:
# create training data
data_x = []
data_y = []
for j in range(temp.shape[0]):
   for i in range(1, temp.shape[1] - 1):
     try: 
       data, sampling_rate = librosa.load('Atraining_normal/'+ temp.iloc[j, 0].split('.')[0] +'.wav', sr=44100 )
       if i==1 : print('Atraining_normal/'+ temp.iloc[j, 0].split('.')[0] +'.wav')
       

       temp_data = data[int(temp.iloc[j, i]):int(temp.iloc[j, i+1])]
#        if i==1 : print(int(temp.iloc[j, i+1]))
       temp_label = temp.iloc[:, i].name.split('.')[0]
 
       data_x.append(temp_data)
       data_y.append(temp_label)
     except:
       pass

Atraining_normal/201102081321.wav
Atraining_normal/201102260502.wav
Atraining_normal/201103090635.wav
Atraining_normal/201103140132.wav
Atraining_normal/201103140822.wav
Atraining_normal/201103151912.wav
Atraining_normal/201103221214.wav
Atraining_normal/201104141251.wav
Atraining_normal/201105011626.wav
Atraining_normal/201105021654.wav
Atraining_normal/201105021804.wav
Atraining_normal/201105151450.wav
Atraining_normal/201106111136.wav
Atraining_normal/201106141148.wav
Atraining_normal/201106210943.wav
Atraining_normal/201106221418.wav
Atraining_normal/201106221450.wav
Atraining_normal/201108011112.wav
Atraining_normal/201108011114.wav
Atraining_normal/201108011115.wav
Atraining_normal/201108011118.wav

In [6]:
# preprocessing 
from keras.preprocessing.sequence import pad_sequences

# step 1
data_x = pad_sequences(data_x, maxlen=20000, dtype='float', padding='post', truncating='post', value=0.)

# step 2
data_x = data_x / np.max(data_x)

# step 3
data_x = data_x[:,:,np.newaxis]
data_y = pd.Series(data_y)
data_y.value_counts()

data_y = data_y.map({'S1':0, 'S2':1}).values

Using TensorFlow backend.

In [7]:
from keras.layers import InputLayer, Conv1D, Dense, Flatten, MaxPool1D
from keras.models import Sequential

model = Sequential()

model.add(InputLayer(input_shape=data_x.shape[1:]))

model.add(Conv1D(filters=50, kernel_size=10, activation='relu'))
model.add(MaxPool1D(strides=8))
model.add(Conv1D(filters=50, kernel_size=10, activation='relu'))
model.add(MaxPool1D(strides=8))
model.add(Flatten())
model.add(Dense(units=1, activation='softmax'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:From /home/samir/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /home/samir/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/samir/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /home/samir/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4267: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /home/samir/anaconda3/lib/python3.7/site-packages/keras/optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From /home/samir/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3657: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From /home/samir/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv1d_1 (Conv1D)            (None, 19991, 50)         550
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 2499, 50)          0
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 2490, 50)          25050
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 312, 50)           0
_________________________________________________________________
flatten_1 (Flatten)          (None, 15600)             0
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 15601
=================================================================
Total params: 41,201
Trainable params: 41,201
Non-trainable params: 0
_________________________________________________________________

In [9]:
# train model
model.fit(data_x, data_y, batch_size=32, epochs=10)

WARNING:tensorflow:From /home/samir/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

Epoch 1/10
369/369 [==============================] - 8s 23ms/step - loss: 8.3384 - acc: 0.4770
Epoch 2/10
369/369 [==============================] - 7s 19ms/step - loss: 8.3384 - acc: 0.4770
Epoch 3/10
369/369 [==============================] - 7s 18ms/step - loss: 8.3384 - acc: 0.4770
Epoch 4/10
369/369 [==============================] - 7s 18ms/step - loss: 8.3384 - acc: 0.4770
Epoch 5/10
369/369 [==============================] - 8s 23ms/step - loss: 8.3384 - acc: 0.4770
Epoch 6/10
369/369 [==============================] - 7s 20ms/step - loss: 8.3384 - acc: 0.4770
Epoch 7/10
369/369 [==============================] - 10s 28ms/step - loss: 8.3384 - acc: 0.4770
Epoch 8/10
369/369 [==============================] - 10s 27ms/step - loss: 8.3384 - acc: 0.4770
Epoch 9/10
369/369 [==============================] - 11s 31ms/step - loss: 8.3384 - acc: 0.4770
Epoch 10/10
369/369 [==============================] - 7s 19ms/step - loss: 8.3384 - acc: 0.4770